[package]
name = "pull_62"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
little_exif = { path = "../../" }
avif-serialize = { git = "https://github.com/haixuantao/avif-serialize" }
rav1e = "0.8.1"
image = "0.24"
ravif = "0.12.0"